name: Build

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
    branches:
      - 'master'

env:
  SOLUTION_NAME: MotionTrackingMKIIPlusforAviUtl2

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: WORKSPACE
        working-directory: ${{ github.workspace }}

      - name: Download OpenCV LICENSE
        run: |
          curl https://raw.githubusercontent.com/opencv/opencv/4.13.0/LICENSE -o opencv.txt

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: |
          (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | py -

      - name: Set up Conan
        run: |
          poetry install
          poetry run conan profile detect --force

      - name: Install Make
        run:
          choco install make

      - name: Build
        run: |
          cd ${{ github.workspace }}
          cd src
          make compile

      - name: Pack into a folder
        run: |
          cd ${{ github.workspace }}
          mkdir pack\${{ env.SOLUTION_NAME }}
          mkdir pack\${{ env.SOLUTION_NAME }}\Licenses

          # 本体
          Copy-Item src\build\build\Release\MotionTrackingMKIIPlusforAviUtl2.aux2 pack\${{ env.SOLUTION_NAME }}

          # MTMK2 のライセンスを名前を変えて複製
          Copy-Item LICENSE ${{ env.SOLUTION_NAME }}.txt
          Copy-Item ${{ env.SOLUTION_NAME }}.txt pack\${{ env.SOLUTION_NAME }}.txt

          # AviUtl のSDKライセンス
          Copy-Item Licenses\aviutl_plugin_sdk.txt pack\${{ env.SOLUTION_NAME }}\Licenses

          # AviUtl2 のSDKライセンス
          Copy-Item src\aviutl2_sdk\license.txt pack\${{ env.SOLUTION_NAME }}\license.txt

          # OpenCV のライセンス
          Copy-Item opencv.txt pack\${{ env.SOLUTION_NAME }}\Licenses\
          Copy-Item opencv.txt pack\${{ env.SOLUTION_NAME }}\Licenses\opencv_contrib.txt

          # README
          Copy-Item README.ja.md pack
          Copy-Item README.md pack

      - name:  Upload artifact
        uses: actions/upload-artifact@v7
        with:
          path: pack\*
          name: ${{ env.SOLUTION_NAME }}

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Compress
        run: |
          cd artifacts
          zip -r ../${{ env.SOLUTION_NAME }}.zip *

      - name: ReleaseNotes
        run: |
          echo '変更内容につきましては[CHANGELOG.md](https://github.com/nullruptr/MotionTracking_MK-II_Plus_for_AviUtl2/blob/master/CHANGELOG.md)をご確認ください' >> ReleaseNotes.txt

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: '*.zip'
          body_path: ReleaseNotes.txt
